GET http://localhost:3005/orders

###
GET http://localhost:3005/orders/1

###
DELETE http://localhost:3005/orders/1

###
POST http://localhost:3005/orders
Content-Type: application/json

{
    "date": "2021-09-01T00:00:00.000Z",
    "totalValue": 200.00,
    "status": "RECEIVED",
    "paymentMethod": "CARTAO",
    "delivery": {
        "name": "Fulano",
        "email": "fulano@email.com",
        "cpf": "123.456.789-00",
        "address": "Rua dos Bobos, 0",
        "complement": "Apto 101",
        "city": "São Paulo",
        "state": "SP"
    },
    "items": [
        {
            "quantity": 1,
            "unitPrice": 100.00,
            "product": {
                "id": 1
            }
        },
        {
            "quantity": 1,
            "unitPrice": 100.00,
            "product": {
                "id": 2
            }
        }
    ]
}
