import products from "./products"

const MAX_NUMBER_OF_INSTALLMENTS = 12
const MIN_NUMBER_OF_INSTALLMENTS = 2
const MONTHLY_INTEREST_RATE = 0.0167

export { 
  products,
  MAX_NUMBER_OF_INSTALLMENTS, 
  MIN_NUMBER_OF_INSTALLMENTS,  
  MONTHLY_INTEREST_RATE
}
