services:
  gam3r-store-postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gstore
