GET http://localhost:3005/products

###
GET http://localhost:3005/products/29

###
DELETE http://localhost:3005/products/29

###
POST http://localhost:3005/products
Content-Type: application/json

{
    "name": "Galaxy S24 Ultra",
    "description": "Samsung Galaxy S24 Ultra é um smartphone top de linha com câmera de 108 MP",
    "brand": "Samsung",
    "model": "Galaxy S24",
    "imageUrl": "https://samsungbrshop.vtexassets.com/arquivos/ids/228347/1---_S767B~1.png",
    "rating": 4.8,
    "reviewVideo": "https://www.youtube.com/watch?v=XaqOejIaFgM",
    "tags": ["smartphone", "celular"],
    "basePrice": 3000.00,
    "promotionalPrice": 2500.00,
    "lowestPrice": 2000.00,
    "highestPrice": 4000.00,
    "averagePrice": 3000.00,
    "specs": {
        "Tela": "6.2 polegadas",
        "Memória": "8 GB",
        "Armazenamento": "128 GB",
        "Câmera": "12 MP",
        "Bateria": "4000 mAh"
    }
}
